# Generated by Django 2.0.6 on 2018-07-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='License',
        ),
    ]
